const { GoogleAuth } = require('google-auth-library');
require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const fs = require('fs');

async function testApi(name, payloadStr) {
  const auth = new GoogleAuth({ scopes: ['https://www.googleapis.com/auth/cloud-platform'] });
  const client = await auth.getClient();
  const token = await client.getAccessToken();
  const project = process.env.GOOGLE_CLOUD_PROJECT || await auth.getProjectId();
  
  const endpoint = `https://us-central1-aiplatform.googleapis.com/v1/projects/${project}/locations/us-central1/publishers/google/models/imagen-3.0-capability-001:predict`;
  console.log(`\n-- Testing: ${name} --`);
  
  const res = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${token.token}`, 'Content-Type': 'application/json' },
    body: payloadStr
  });

  const json = await res.json();
  if (json.error) {
    console.error(`FAILED:`, JSON.stringify(json.error, null, 2));
  } else {
    console.log(`SUCCESS! Generated bytes length: ${json.predictions?.[0]?.bytesBase64Encoded?.length}`);
  }
}

async function run() {
  const b64 = fs.readFileSync('C:/Users/Oester/.gemini/antigravity/brain/1dcd2160-140b-45f4-96cb-b966ffe9747d/test_valid_png_1776806938663.png').toString('base64');
  
  const p1 = { prompt: 'a red car' };
  const refPayload = {
    referenceImage: { bytesBase64Encoded: b64, mimeType: 'image/png' },
    referenceId: 1,
    referenceType: 'REFERENCE_TYPE_RAW'
  };
  
  const payloads = [
    { name: '1. DEFAULT No mask', data: { instances: [{ prompt: 'a red car', referenceImages: [refPayload] }], parameters: { editMode: 'EDIT_MODE_DEFAULT', numberOfImages: 1, outputMimeType: 'image/jpeg' } } }
  ];

  for (const p of payloads) {
    await testApi(p.name, JSON.stringify(p.data));
  }
}
run();
